1. Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it
enhance Python's capabilities for numerical operations?

Ans: Numpy has been built using C which is the fastest programming language after C++ so because of that it is very fast. Also, unlike the python lists which stores heterogeneous data , Numpy arrays only store homogeneous data i.e the elements in the array can only be of same datatype. Furthermore, the elements in the numpy array are stored at contigous memory locations which enchnace the memory accessing capability thus enhancing the data operations significantly as compared to python lists.


2. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the
other?

Ans: np.mean() and np.average() both are used to calculate the mean of the elements of the array. But when we need to calculate the weighted average then np.average() is preferred. So, np.mean() is used to calculate only the arithmetic mean i.e. all the elements in the array has equal weights.
Syntax : np.mean(array , axis = None)

np.average() is used to calculate the arithmetic and weighted average i.e. the elements in the numpy array may or may not have equal weights. Syntax: np.average(array,axis=None,weight = None)


3. Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D
arrays.

Ans: Methods for reversing the Numpy arrays:
1. By using Flip : np.flip(numpy_arr)
2. By list slicing : numpy_arr[::-1]

In [ ]:
import numpy as np
# 2-D Array
arr_1 = np.random.randint(1,10,(2,2))
print(arr_1)
print(np.flip(arr_1))
print(arr_1[::-1,::-1])


# 1-D Array
arr_2 = np.random.randint(1,10,5)
print(arr_2)
print(np.flip(arr_2))
print(arr_2[::-1])

[[4 1]
 [9 1]]
[[1 9]
 [1 4]]
[[1 9]
 [1 4]]
[3 6 8 1 6]
[6 1 8 6 3]
[6 1 8 6 3]


4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types
in memory management and performance.

  Ans: To determine the data type of a numpy array , we use dtype keyword. In python list we can store heterogeneous data i.e. elements having different data types can be stored in it. Due to which the elements of the array are stored at different memory locations. But in numpy array elements of same data type are stored which are stored at contigous memory locations. Bcoz of this the access is faster thus increasing the performance by making operations faster.

In [ ]:
arr_1.dtype

dtype('int64')

5. Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?

Ans: Nd arrays are called as N-dimensional arrays.Key Features:

1. They can be used to represent any dimension array(1D,2D etc.)

2. The elements are stored at contigous memory locations.

3. The elements can only be of same data type.

4. Indexing and slicing can be used to access array elements.

5. Numpy arrays are built using C which makes the scientific operations faster.

Unlike python list which can store heterogeneous data . Also the data are not stored in contigous form.

6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.

Ans: The python lists stores heterogeneous data whereas Numpy arrays only store homogeneous data i.e the elements in the array are of same datatype. Furthermore, the elements in the numpy array are stored at contigous memory locations which enchnace the memory accessing capability thus enhancing the data operations significantly as compared to python lists.

7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and
output

Ans: vstack() and hstack() funcions stands for vertical stack and horizontal stack respectively. Both these functions are used to stack two or more arrays vertically or horizontally. vstack() is used to stack two or more arrays vertically thus increasing the number of columns which is the sum of column nos of all the arrays. Similarly, hstack() is used to stack two or more arrays horizontally thus increasing the number of rows in the resultant array.

In [ ]:
import numpy as np
arr_3 = np.random.randint(1,100,(5,5))
arr_4 = np.random.randint(5,40,(5,5))

vert_arr = np.vstack((arr_3,arr_4))
hor_arr=np.hstack((arr_3,arr_4))
print(arr_3)
print(arr_4)
print(vert_arr)
print(hor_arr)

[[76 43 90 54 45]
 [ 1  4 18 97 37]
 [11 23 14 71 30]
 [86 67 54 20 41]
 [10 11 56 60 18]]
[[21 30  9  9 16]
 [15 29 35 17 32]
 [18 36 24 15 38]
 [22 14 36 11 17]
 [17 38 12 31 19]]
[[76 43 90 54 45]
 [ 1  4 18 97 37]
 [11 23 14 71 30]
 [86 67 54 20 41]
 [10 11 56 60 18]
 [21 30  9  9 16]
 [15 29 35 17 32]
 [18 36 24 15 38]
 [22 14 36 11 17]
 [17 38 12 31 19]]
[[76 43 90 54 45 21 30  9  9 16]
 [ 1  4 18 97 37 15 29 35 17 32]
 [11 23 14 71 30 18 36 24 15 38]
 [86 67 54 20 41 22 14 36 11 17]
 [10 11 56 60 18 17 38 12 31 19]]


8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various
array dimensions.

Ans: fliplr() and flipur() functions are used to reverse the elements order in a N-dimensional numpy array. fliplr() - flip left to right- flips the array from left to right i.e. reverse the column elements. flipud() - flip up to dowm - flips the array from upward to downward - reverse the rows.

In [ ]:
import numpy as np
arr_1 = np.random.randint(1,10,(2,3))

print(arr_1)

print(np.fliplr(arr_1))
print(np.flipud(arr_1))

[[9 5 1]
 [4 7 9]]
[[1 5 9]
 [9 7 4]]
[[4 7 9]
 [9 5 1]]


9. Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?

Ans: array_split() method in numpy is used to split an array into multiple subarrays.

Syntax: np.array_split(array , sections , axis)

When the array cannot be divided into subarrays of equal sizes , then in that case the array is divided into subarrays of unequal sizes in which the first few subarrays may have more elements than the rest subarrays.

10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array
operations?

Ans: Vectroization is the concept of numpy in which the array operations are performed all at once but broadcasting is the concept used in numpy to perform operations in which the array operation is divided into smaller tasks to perform operations on different shape arrays.

### ***PRACTICAL QUESTIONS***


1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

In [ ]:
import numpy as np
arr = np.random.randint(1,100,(3,3))
print(arr)
print(arr.T)

[[25 64 63]
 [37 51  2]
 [36 27 67]]
[[25 37 36]
 [64 51 27]
 [63  2 67]]


2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

In [ ]:
arr_1 = np.random.randint(1,100,10)
print(arr_1)
print(arr_1.reshape(2,5))
print(arr_1.reshape(5,2))

[53 35 41 43 67 57 85  3 44 37]
[[53 35 41 43 67]
 [57 85  3 44 37]]
[[53 35]
 [41 43]
 [67 57]
 [85  3]
 [44 37]]


3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

In [ ]:
arr_2 = np.random.random_sample((4,4))
print(arr_2)
zero_arr = np.zeros((6,6))
zero_arr[1:5,1:5] = arr_2
print(zero_arr)

[[0.62813936 0.1379699  0.13737316 0.25992849]
 [0.94194882 0.08414094 0.37629358 0.57519304]
 [0.30187325 0.5138695  0.06250474 0.4531989 ]
 [0.71288084 0.98335868 0.04955337 0.13322961]]
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.62813936 0.1379699  0.13737316 0.25992849 0.        ]
 [0.         0.94194882 0.08414094 0.37629358 0.57519304 0.        ]
 [0.         0.30187325 0.5138695  0.06250474 0.4531989  0.        ]
 [0.         0.71288084 0.98335868 0.04955337 0.13322961 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.

In [ ]:
rand_arr = np.arange(10,60,5)
print(rand_arr)

[10 15 20 25 30 35 40 45 50 55]


5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations
(uppercase, lowercase, title case, etc.) to each element.

In [ ]:
str_arr = np.array(['python','numpy','pandas'])
print(np.char.upper(str_arr))
print(np.char.lower(str_arr))
print(np.char.capitalize(str_arr))


['PYTHON' 'NUMPY' 'PANDAS']
['python' 'numpy' 'pandas']
['Python' 'Numpy' 'Pandas']


6. Generate a NumPy array of words. Insert a space between each character of every word in the array

In [ ]:
word_arr = np.array(["simran" , "singh"])


7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

In [ ]:
arr1 = np.random.randint(1,40,(5,4))
arr2 = np.random.randint(1,40,(5,4))
print(arr1)
print(arr2)
print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)
print(arr1/arr2)

[[25 30 29 32]
 [ 9 13 31 31]
 [12  2 31 31]
 [20  6 38 10]
 [ 7 33 26 28]]
[[29 26  5  4]
 [ 1 23 14  2]
 [29 22 22 32]
 [15 29  4 21]
 [ 5 24 10 10]]
[[54 56 34 36]
 [10 36 45 33]
 [41 24 53 63]
 [35 35 42 31]
 [12 57 36 38]]
[[ -4   4  24  28]
 [  8 -10  17  29]
 [-17 -20   9  -1]
 [  5 -23  34 -11]
 [  2   9  16  18]]
[[725 780 145 128]
 [  9 299 434  62]
 [348  44 682 992]
 [300 174 152 210]
 [ 35 792 260 280]]
[[ 0.86206897  1.15384615  5.8         8.        ]
 [ 9.          0.56521739  2.21428571 15.5       ]
 [ 0.4137931   0.09090909  1.40909091  0.96875   ]
 [ 1.33333333  0.20689655  9.5         0.47619048]
 [ 1.4         1.375       2.6         2.8       ]]


8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

In [ ]:
arr = np.eye(5)
arr[arr==1]

array([1., 1., 1., 1., 1.])

9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in
this array.

In [ ]:
import numpy as np
prime_arr = np.random.randint(1,1000,100)
lis = []
flag = False
for j in prime_arr:
  flag = False
  for i in range(2,j//2+1):
    if(j%i == 0):
      flag = True
  if(flag == False):
    lis.append(j)

print(prime_arr)
print(lis)

[ 74 653 978 829 522 362 270 906 422 924 636 487 608  17 796  20 385 119
 957 105 523 813 577 683 492 358 734 926 607  31 799 688 748 257 228 699
 314 968 235  89 187 514 732 591 677 644 493 429 353 960 337 332 538 708
 588 256  21 618 375 685 297 235 309 110 219 416 519 763 211  96 817 271
 940 789 753 803 611 154  61 243 311 491 759 670 621 332 785 654 990 589
 876 998 360 327 293 287 610  36 408 579]
[653, 829, 487, 17, 523, 577, 683, 607, 31, 257, 89, 677, 353, 337, 211, 271, 61, 311, 491, 293]


10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly
averages.

In [ ]:
temp_arr = np.random.randint(10,20,30)
no_of_week = len(temp_arr)//7
no_of_day = no_of_week * 7
temp_arr = temp_arr[:no_of_day]
new_arr = temp_arr.reshape(no_of_week,7)
print(np.mean(new_arr,axis = 1))
print(temp_arr)

[13.71428571 13.71428571 16.14285714 13.71428571]
[10 18 13 14 11 14 16 17 11 15 13 14 12 14 18 17 12 13 16 18 19 16 12 11
 16 13 11 17]


In [ ]:
_